# Site settings
language:               "en"
title:                  "Current Research in Digital History"
description:            "Hosted by the Roy Rosenzweig Center for History and New Media, Current Research in Digital History is an annual one-day conference that publishes online, peer-reviewed proceedings. Its primary aim is to encourage and publish scholarship in digital history that offers discipline-specific arguments and interpretations."
google-verification:    ""
current_volume: "2019"

collections:
  essays:
    output: true

defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: post

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "vendor"

# Plugins

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge

# CRDH

appendices:       "http://crdh.rrchnm.org/appendices"
current_volume:   "2019"
current_number:   "2"
