name: Build and Deliver

on:
  push:
    branches:
      - "main"
      - "preview"
      - "feature/**"

  pull_request:
    branches: [ "main" ]
    types:
      - ready_for_review
      - review_requested

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deliver:
    
    permissions:
      packages: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
  
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  
      - name: Build and push backend (prod)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            configfile=_config-production.yml

      - name: Build and push backend (devl)
        if: github.ref == 'refs/heads/preview' || startsWith(github.ref, 'refs/heads/feature')
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            configfile=_config-dev.yml
